language: node_js
sudo: true
dist: trusty
node_js:
  - 4
  - 5
  - 6
install:
  - npm i
script: npm test
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
  - npm run coveralls
